---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-x509-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-x509-secrets
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-x509-secrets
    spec:
      serviceAccountName: {{ template "servicex.fullname" . }}
      # Before launching the main container, copy the certs and set their permissions accordingly
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3.6
          command: ["/bin/sh","-c"]
          args: ["cp /etc/grid-certs-ro/usercert.pem /etc/grid-certs; chmod 600 /etc/grid-certs/usercert.pem; cp /etc/grid-certs-ro/userkey.pem /etc/grid-certs; chmod 400 /etc/grid-certs/userkey.pem"]
          env:
            - name: INSTANCE_NAME
              value: {{ .Release.Name }}
          volumeMounts:
          - name: grid-certs-rw-copy
            mountPath: /etc/grid-certs/
          - name: grid-secret
            mountPath: /etc/grid-certs-ro/
      containers:
      - name: {{ .Release.Name }}-x509-secrets
        image: {{ .Values.x509Secrets.image }}:{{ .Values.x509Secrets.tag }}
        command: ["bash","-c"]
        args: ["python3 x509_updater.py --secret {{ .Release.Name }}-x509-proxy --voms {{ .Values.x509Secrets.vomsOrg }}"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.x509Secrets.pullPolicy }}
        volumeMounts:
          - name: grid-certs-rw-copy
            mountPath: /etc/grid-certs/
          - name: grid-secret
            mountPath: /etc/grid-certs-ro/

      volumes:
        # Mount the usercert, userkey, and passphrase file. These will have the
        # wrong permissions to be used for generating the voms proxy
        - name: grid-secret
          secret:
            secretName: grid-certs-secret  # Installed via servicex command line

        # Create an empty dir to share between the init container and the main
        # container. The init container will copy the certs from grid-secret
        # to this dir and set the correct permissions
        - name: grid-certs-rw-copy
          emptyDir: {}

