---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-preflight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-preflight
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-preflight
    spec:
      containers:
      - name: {{ .Release.Name }}-preflight
        image: {{ .Values.preflight.image }}:{{ .Values.preflight.tag }}
        command: ["bash","-c"]
        env:
          - name: "BASH_ENV"
            value: "/servicex/.bashrc"
          - name: INSTANCE_NAME
            value: {{ .Release.Name }}
        args: ["/servicex/proxy-exporter.sh & sleep 5 && python /servicex/validate_requests.py --rabbit-uri amqp://user:{{.Values.rabbitmq.auth.password}}@{{ .Release.Name }}-rabbitmq:5672/%2F"]
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.preflight.pullPolicy }}
        volumeMounts:
          - name: x509-secret
            mountPath: /etc/grid-security-ro
            readOnly: true

          {{ if .Values.hostMount }}
          - name: rootfiles
            mountPath: /data
          {{ end }}
      volumes:
        - name: x509-secret
          secret:
            defaultMode: 292
            secretName: {{ .Release.Name }}-x509-proxy
        {{ if .Values.hostMount }}
        - name: rootfiles
          hostPath:
            path: {{ .Values.hostMount }}
        {{ end }}

