apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rucio-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  rucio.cfg: |
    [client]
    rucio_host = {{ .Values.didFinder.rucio_host }}
    auth_host = {{ .Values.didFinder.auth_host }}
    auth_type = x509_proxy
    ca_cert = /etc/pki/tls/certs/ca-bundle.crt
    account = {{ .Values.gridAccount }}
    client_x509_proxy = $X509_USER_PROXY
    request_retries = 3

    [policy]
    permission = {{ .Values.x509Secrets.vomsOrg }}
    schema = {{ .Values.x509Secrets.vomsOrg }}
    lfn2pfn_algorithm_default = hash

